### ISSUE TITLE
PCL Support?

### ISSUE THREAD

**Issue by eanagel** [wasabii/OLinq#11]
I'd love to use OLinq in my PCL project, is it possible to compile it as portable?

**Comment by wasabii** [comment]
Depends what PCL has. The core of hte library is in a Source Code only project, which is referenced by a .Net 4.5 and Silverlight project, with some compile flags that adjust it slightly for each. So, PCL support just needs a PCL project, and whatever modifications one needs to get it building.

**Comment by wasabii** [comment]
I added a -pcl project which includes MonoAndroid and MonoTouch support, Windows 8 and Windows Phone. Because I wanted that. I'm unsure what platforms you were asking for when you opened this issue. But a PCL project is available now.
